apiVersion: v1
kind: Secret
metadata:
  name: payment-db-secret
type: Opaque
stringData:
  POSTGRES_USER: postgres
  POSTGRES_PASSWORD: your_password
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: payment-service-config
data:
  POSTGRES_DB: PaymentDb
  ASPNETCORE_ENVIRONMENT: Production
  # Will route to the Billing Service in the cluster
  BillingServiceBaseUrl: "http://billing-service:8080" 
  ConnectionStrings__DefaultConnection: "Host=payment-db;Port=5432;Database=PaymentDb;Username=postgres;Password=your_password;"
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: payment-db-pvc
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
---
# ------------------- DATABASE -------------------
apiVersion: apps/v1
kind: Deployment
metadata:
  name: payment-db
spec:
  selector:
    matchLabels:
      app: payment-db
  template:
    metadata:
      labels:
        app: payment-db
    spec:
      containers:
        - name: postgres
          image: postgres:16-alpine
          ports:
            - containerPort: 5432
          envFrom:
            - configMapRef:
                name: payment-service-config
            - secretRef:
                name: payment-db-secret
          volumeMounts:
            - mountPath: /var/lib/postgresql/data
              name: payment-db-data
      volumes:
        - name: payment-db-data
          persistentVolumeClaim:
            claimName: payment-db-pvc
---
apiVersion: v1
kind: Service
metadata:
  name: payment-db
spec:
  selector:
    app: payment-db
  ports:
    - port: 5432
      targetPort: 5432
---
# ------------------- PAYMENT API -------------------
apiVersion: apps/v1
kind: Deployment
metadata:
  name: payment-service
  labels:
    app: payment-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: payment-service
  template:
    metadata:
      labels:
        app: payment-service
      annotations:
        prometheus.io/scrape: "true"
        prometheus.io/path: "/metrics"
        prometheus.io/port: "8080"
    spec:
      containers:
        - name: payment-service
          image: payment-service:latest # Ensure you build this inside Minikube's docker env
          imagePullPolicy: Never
          ports:
            - containerPort: 8080
          envFrom:
            - configMapRef:
                name: payment-service-config
          livenessProbe:
            httpGet:
              path: /health
              port: 8080
            initialDelaySeconds: 15
            periodSeconds: 10
          readinessProbe:
            httpGet:
              path: /health
              port: 8080
            initialDelaySeconds: 5
            periodSeconds: 5
---
apiVersion: v1
kind: Service
metadata:
  name: payment-service
spec:
  type: NodePort
  selector:
    app: payment-service
  ports:
    - port: 8080
      targetPort: 8080
      nodePort: 30002